---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
http.host: 0.0.0.0

node.name: logstash
# xpack:
#   monitoring:
#     enabled: true
#     elasticsearch:
#       username: 'elastic'
#       password: 'changeme'
#       hosts: ["https://elasticsearch:9200"]
#       ssl:
#         verification_mode: none