name: capstone

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "frontend"
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Run Typecheck
        run: yarn typecheck --noEmit --noErrorTruncation --pretty false --incremental false --watch false --skipLibCheck

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "frontend"
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Run Format
        run: yarn format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "frontend"
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Run Lint
        run: yarn lint

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: "frontend"
      - uses: actions/setup-node@v2
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Lint commit message
        run: yarn lint:commit
